title: Tu título genial
author: Usuario GitHub
email: tu-email@dominio.com
description: > # this means to ignore newlines until "baseurl:"
  Escribe aquí una descripción genial para tu nuevo sitio. Puedes editar
  esta línea en _config.yml. Aparecerá en la metainformación de cabecera
  de tu documento (para los resultados de búsqueda de Google) y en la
  descripción de tu sitio en feed.xml.

# links a redes sociales
twitter_username: tu-usuario-de-twitter
github_username:  tu-usuario-de-github

show_excerpts: true # pon false para no mostrar los extractos en la página principal
